# Generated by Django 4.0.4 on 2022-06-03 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_workout_sets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sets', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
