# Generated by Django 4.0.4 on 2022-06-04 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_set_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='multiple',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='workoutset',
            name='multiple',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
