# Generated by Django 4.0.4 on 2022-06-04 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_set_multiple_workoutset_multiple_alter_exercise_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='exercise',
            field=models.ManyToManyField(related_name='SetExercise', to='api.exercise'),
        ),
        migrations.AlterField(
            model_name='workoutset',
            name='exercise',
            field=models.ManyToManyField(related_name='Exercise', to='api.exercise'),
        ),
    ]
