# Generated by Django 4.0.5 on 2022-06-25 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_workout_sets'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutset',
            name='setNum',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
